apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiny-container
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm
    repoURL: https://github.com/puszczyk16/tiny-container.git
    targetRevision: HEAD
    helm:
      values: |
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
